<?php
declare(strict_types=1);
if(session_status()===PHP_SESSION_NONE)session_start();
require_once __DIR__.'/conexao.php'; require_once __DIR__.'/sidebar_integration.php';
if(empty($_SESSION['perm_administrativo'])&&empty($_SESSION['perm_superadmin'])){http_response_code(403);exit('Acesso negado');}
$tab=$_GET['tab']??'leads'; $msg='';
if($_SERVER['REQUEST_METHOD']==='POST'&&$pdo){
  if(!hash_equals($_SESSION['og_csrf']??'',$_POST['csrf']??''))exit('Token inválido');
  try{
    $kind=$_POST['kind']??'';
    if($kind==='toggle'){$table=['unidade'=>'orcamento_unidades','pacote'=>'orcamento_pacotes','regra'=>'orcamento_regras'][$_POST['entity']??'']??'';if($table){$s=$pdo->prepare("UPDATE $table SET ativo=NOT ativo WHERE id=:id");$s->execute([':id'=>(int)$_POST['id']]);}}
    if($kind==='unit'){$s=$pdo->prepare('INSERT INTO orcamento_unidades(nome,descricao,capacidade_min,capacidade_max,tipos_evento,video_url) VALUES(:n,:d,:a,:b,CAST(:t AS jsonb),:v)');$s->execute([':n'=>trim($_POST['nome']),':d'=>$_POST['descricao'],':a'=>(int)$_POST['min'],':b'=>(int)$_POST['max'],':t'=>json_encode($_POST['tipos']??[]),':v'=>$_POST['video']?:null]);}
    if($kind==='package'){
      $pdfUrl=trim((string)($_POST['pdf']??''));
      if(isset($_FILES['pdf_file'])&&($_FILES['pdf_file']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){
        $f=$_FILES['pdf_file'];
        if(($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Falha ao receber o PDF. Código '.($f['error']??''));
        $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);
        if($mime!=='application/pdf'||strtolower(pathinfo($f['name'],PATHINFO_EXTENSION))!=='pdf')throw new RuntimeException('Selecione um arquivo PDF válido.');
        require_once __DIR__.'/magalu_storage_helper.php';
        $storage=new MagaluStorageHelper();
        $uploaded=$storage->uploadFile($f,'orcamentos/catalogos',50*1024*1024,['pdf']);
        if(empty($uploaded['success'])||empty($uploaded['url']))throw new RuntimeException($uploaded['error']??'O upload não foi concluído.');
        $pdfUrl=$uploaded['url'];
      }
      if($pdfUrl===''||!filter_var($pdfUrl,FILTER_VALIDATE_URL))throw new RuntimeException('Envie um PDF ou informe uma URL válida.');
      $s=$pdo->prepare('INSERT INTO orcamento_pacotes(unidade_id,nome,tipo_evento,perfil,formato_gastronomico,convidados_min,convidados_max,pdf_url,video_url,descricao,prioridade) VALUES(:u,:n,:t,:p,:f,:a,:b,:pdf,:v,:d,:o)');$s->execute([':u'=>(int)$_POST['unidade'],':n'=>trim($_POST['nome']),':t'=>$_POST['tipo'],':p'=>$_POST['perfil']?:null,':f'=>$_POST['formato']?:null,':a'=>(int)$_POST['min'],':b'=>(int)$_POST['max'],':pdf'=>$pdfUrl,':v'=>$_POST['video']?:null,':d'=>$_POST['descricao'],':o'=>(int)$_POST['prioridade']]);
    }
    $msg='Alteração salva.';
  }catch(Throwable $e){$msg='Erro: '.$e->getMessage();}
}
$_SESSION['og_csrf']=bin2hex(random_bytes(24));$csrf=$_SESSION['og_csrf'];
$units=$pdo?$pdo->query('SELECT * FROM orcamento_unidades ORDER BY nome')->fetchAll():[];
$packs=$pdo?$pdo->query('SELECT p.*,u.nome unidade FROM orcamento_pacotes p JOIN orcamento_unidades u ON u.id=p.unidade_id ORDER BY p.prioridade,p.nome')->fetchAll():[];
$leads=$pdo?$pdo->query('SELECT * FROM orcamento_leads ORDER BY criado_em DESC LIMIT 300')->fetchAll():[];
includeSidebar('Orçamento Guiado');
?><style>.og{max-width:1250px;margin:auto;padding:24px}.og nav{display:flex;gap:8px;flex-wrap:wrap}.og nav a,.og button{padding:10px 14px;border:0;border-radius:10px;background:#163b8f;color:#fff;text-decoration:none}.og section{background:#fff;padding:20px;border-radius:16px;margin-top:18px;box-shadow:0 4px 18px #0001}.og table{width:100%;border-collapse:collapse}.og th,.og td{text-align:left;padding:10px;border-bottom:1px solid #eee}.og input,.og select,.og textarea{padding:11px;border:1px solid #ccd4e3;border-radius:8px;width:100%}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.scroll{overflow:auto}.pill{padding:4px 8px;border-radius:99px;background:#eef3ff}</style><div class="og"><h1>Orçamento Guiado</h1><p>Administre os conteúdos do link público. Nenhuma alteração exige editar o frontend.</p><nav><?php foreach(['leads'=>'Leads','unidades'=>'Unidades','pacotes'=>'Pacotes','regras'=>'Regras'] as $k=>$v):?><a href="?page=administrativo_orcamentos&tab=<?=$k?>"><?=$v?></a><?php endforeach;?><a href="?page=orcamento_guiado" target="_blank">Abrir link público ↗</a></nav><?php if($msg):?><p class="pill"><?=htmlspecialchars($msg)?></p><?php endif;?>
<?php if($tab==='leads'):?><section><h2>Leads recentes</h2><div class="scroll"><table><tr><th>Data</th><th>Cliente</th><th>WhatsApp</th><th>Evento</th><th>Data evento</th><th>Convidados</th><th>Recomendação</th></tr><?php foreach($leads as $l):?><tr><td><?=htmlspecialchars(date('d/m/Y H:i',strtotime($l['criado_em'])))?></td><td><?=htmlspecialchars($l['nome'])?></td><td><?=htmlspecialchars($l['whatsapp'])?></td><td><?=htmlspecialchars($l['tipo_evento'])?></td><td><?=htmlspecialchars($l['data_evento']??'')?></td><td><?=(int)$l['convidados']?></td><td><?=htmlspecialchars(($l['unidade_recomendada']??'').' '.($l['pacote_recomendado']??''))?></td></tr><?php endforeach;?></table></div></section>
<?php elseif($tab==='unidades'):?><section><h2>Nova unidade</h2><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="kind" value="unit"><div class="grid"><input name="nome" placeholder="Nome" required><input name="min" type="number" placeholder="Capacidade mínima" required><input name="max" type="number" placeholder="Capacidade máxima" required><input name="video" placeholder="URL do vídeo"></div><textarea name="descricao" placeholder="Descrição"></textarea><div><?php foreach(['casamento','bodas','15anos','infantil'] as $t):?><label><input style="width:auto" type="checkbox" name="tipos[]" value="<?=$t?>"> <?=$t?></label> <?php endforeach;?></div><button>Adicionar</button></form></section><section><table><tr><th>Unidade</th><th>Capacidade</th><th>Status</th><th></th></tr><?php foreach($units as $u):?><tr><td><?=htmlspecialchars($u['nome'])?></td><td><?=$u['capacidade_min']?>–<?=$u['capacidade_max']?></td><td><?=$u['ativo']?'Ativa':'Inativa'?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="kind" value="toggle"><input type="hidden" name="entity" value="unidade"><input type="hidden" name="id" value="<?=$u['id']?>"><button>Alternar</button></form></td></tr><?php endforeach;?></table></section>
<?php elseif($tab==='pacotes'):?><section><h2>Novo pacote / catálogo</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="kind" value="package"><div class="grid"><select name="unidade"><?php foreach($units as $u):?><option value="<?=$u['id']?>"><?=htmlspecialchars($u['nome'])?></option><?php endforeach;?></select><input name="nome" placeholder="Nome do pacote" required><select name="tipo"><?php foreach(['casamento','bodas','15anos','infantil'] as $t):?><option><?=$t?></option><?php endforeach;?></select><select name="perfil"><option value="">Qualquer perfil</option><option value="economico">Econômico</option><option value="equilibrado">Equilibrado</option><option value="completo">Completo</option></select><input name="formato" placeholder="Formato gastronômico"><input name="min" type="number" placeholder="Mínimo" required><input name="max" type="number" placeholder="Máximo" required><input name="prioridade" type="number" value="100" placeholder="Prioridade"><label>Enviar PDF (máx. 50 MB)<input name="pdf_file" type="file" accept="application/pdf,.pdf"></label><input name="pdf" type="url" placeholder="Ou cole uma URL pública"><input name="video" type="url" placeholder="URL do vídeo"></div><p>Ao selecionar um arquivo, ele será enviado para <code>orcamentos/catalogos</code> no Magalu e a URL será salva automaticamente.</p><textarea name="descricao" placeholder="Descrição resumida"></textarea><button>Enviar e adicionar</button></form></section><section class="scroll"><table><tr><th>Unidade</th><th>Pacote</th><th>Evento</th><th>PDF</th><th>Status</th><th></th></tr><?php foreach($packs as $p):?><tr><td><?=htmlspecialchars($p['unidade'])?></td><td><?=htmlspecialchars($p['nome'])?></td><td><?=htmlspecialchars($p['tipo_evento'])?></td><td><?=$p['pdf_url']?'<a target="_blank" href="'.htmlspecialchars($p['pdf_url']).'">Abrir</a>':'—'?></td><td><?=$p['ativo']?'Ativo':'Inativo'?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="kind" value="toggle"><input type="hidden" name="entity" value="pacote"><input type="hidden" name="id" value="<?=$p['id']?>"><button>Alternar</button></form></td></tr><?php endforeach;?></table></section>
<?php else:?><section><h2>Regras de recomendação</h2><p>A tabela está preparada para prioridades, principal/alternativa, dia, perfil e alimentação. Nesta primeira versão, as faixas obrigatórias são protegidas pelo motor e os conteúdos/pacotes ativos vêm do painel.</p><p>As prioridades específicas de domingo e almoço devem ser cadastradas na migration antes da publicação.</p></section><?php endif;?></div><?php endSidebar();
