<?php
declare(strict_types=1);
require_once __DIR__.'/conexao.php';
require_once __DIR__.'/core/orcamento_recomendador.php';

function og_json(array $x, int $status=200): never { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); echo json_encode($x, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function og_body(): array { return json_decode((string)file_get_contents('php://input'), true) ?: []; }
function og_phone(string $v): ?string { $n=preg_replace('/\D+/', '', $v); if(str_starts_with($n,'00'))$n=substr($n,2); if(strlen($n)===10||strlen($n)===11)$n='55'.$n; return strlen($n)>=12&&strlen($n)<=15 ? '+'.$n : null; }
function og_uuid(string $v): bool { return (bool)preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',$v); }

$action=$_GET['action']??'';
if($action){
  if($_SERVER['REQUEST_METHOD']!=='POST') og_json(['ok'=>false,'erro'=>'Método inválido.'],405);
  $b=og_body(); $sid=(string)($b['sessao_uuid']??'');
  if(!og_uuid($sid)) og_json(['ok'=>false,'erro'=>'Sessão inválida.'],422);
  if($action==='metric' && $pdo){
    $allowed=['inicio','tipo_evento','etapa_respondida','abandono','recomendacao_exibida','pdf_aberto','video_reproduzido','whatsapp','visita','conclusao'];
    if(in_array($b['evento']??'', $allowed,true)){$s=$pdo->prepare('INSERT INTO orcamento_metricas(sessao_uuid,evento,dados) VALUES(:s,:e,CAST(:d AS jsonb))');$s->execute([':s'=>$sid,':e'=>$b['evento'],':d'=>json_encode($b['dados']??[])]);}
    og_json(['ok'=>true]);
  }
  if($action==='lead'){
    if(!empty($b['website'])) og_json(['ok'=>false,'erro'=>'Não foi possível enviar.'],422);
    $phone=og_phone((string)($b['whatsapp']??''));
    if(trim((string)($b['nome']??''))===''||!$phone||empty($b['consentimento'])) og_json(['ok'=>false,'erro'=>'Revise nome, WhatsApp e aceite.'],422);
    $r=$b['respostas']??[]; $rec=OrcamentoRecomendador::recomendar($r);
    if(!$pdo) og_json(['ok'=>false,'erro'=>'Serviço temporariamente indisponível.'],503);
    $count=$pdo->prepare("SELECT count(*) FROM orcamento_leads WHERE criado_em > now()-interval '1 hour' AND whatsapp=:w");$count->execute([':w'=>$phone]);
    if((int)$count->fetchColumn()>=5) og_json(['ok'=>false,'erro'=>'Muitas tentativas. Fale com nossa equipe.'],429);
    $s=$pdo->prepare('INSERT INTO orcamento_leads(nome,whatsapp,email,tipo_evento,data_evento,convidados,respostas,unidade_recomendada,pacote_recomendado,segunda_opcao,consentimento,origem,sessao_uuid) VALUES(:n,:w,:e,:t,:d,:q,CAST(:r AS jsonb),:u,:p,:o,true,:g,:s) RETURNING id');
    $s->execute([':n'=>trim($b['nome']),':w'=>$phone,':e'=>filter_var($b['email']??'',FILTER_VALIDATE_EMAIL)?:null,':t'=>$r['tipo_evento']??'',':d'=>$r['data_evento']?:null,':q'=>(int)($r['convidados']??0),':r'=>json_encode($r),':u'=>$rec['unidades'][0]??'Análise da equipe',':p'=>$rec['pacote'],':o'=>$rec['unidades'][1]??null,':g'=>substr((string)($b['origem']??'orcamento-guiado'),0,80),':s'=>$sid]);
    og_json(['ok'=>true,'lead_id'=>$s->fetchColumn(),'recomendacao'=>$rec,'whatsapp_texto'=>OrcamentoRecomendador::whatsapp($r,$rec)]);
  }
  og_json(['ok'=>false,'erro'=>'Ação inválida.'],404);
}

$catalogos=[];
if($pdo){try{$q=$pdo->query("SELECT p.id,p.nome,p.tipo_evento,p.perfil,p.formato_gastronomico,p.pdf_url,p.video_url,p.descricao,p.diferenciais,u.nome unidade,u.descricao unidade_descricao,u.imagens,u.video_url unidade_video FROM orcamento_pacotes p JOIN orcamento_unidades u ON u.id=p.unidade_id WHERE p.ativo AND u.ativo ORDER BY p.prioridade,p.id");$catalogos=$q->fetchAll();}catch(Throwable $e){error_log($e->getMessage());}}
$wa=preg_replace('/\D+/','',(string)(getenv('ORCAMENTO_WHATSAPP')?:'5511999999999'));
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#163b8f"><title>Monte seu evento | Grupo Smile</title>
<style>
:root{--blue:#163b8f;--gold:#c69a3b;--ink:#17223b;--muted:#667085;--bg:#f5f7fb}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;background:linear-gradient(145deg,#eef3ff,#fff 55%,#fff8e8);color:var(--ink);min-height:100vh}.shell{max-width:760px;margin:auto;padding:18px}.brand{display:flex;align-items:center;gap:12px;font-weight:800;color:var(--blue);padding:8px 2px}.mark{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:var(--blue);color:#fff;border:3px solid var(--gold)}.progress{height:7px;background:#dce3f1;border-radius:10px;overflow:hidden;margin:16px 0}.bar{height:100%;background:linear-gradient(90deg,var(--blue),var(--gold));transition:.35s}.card{background:#fffffff2;border:1px solid #e4e8f0;border-radius:24px;box-shadow:0 18px 50px #163b8f18;padding:clamp(22px,5vw,42px);min-height:440px;animation:in .25s ease}@keyframes in{from{opacity:0;transform:translateY(8px)}}h1{font-size:clamp(26px,6vw,40px);line-height:1.1;margin:0 0 10px}p{color:var(--muted);line-height:1.55}.options{display:grid;gap:12px;margin-top:24px}.option,.primary,.secondary{font:inherit;border-radius:15px;padding:17px 18px;cursor:pointer;text-align:left;border:1px solid #d7ddea;background:#fff;color:var(--ink);font-weight:700;transition:.18s}.option:hover,.option:focus{border-color:var(--gold);transform:translateY(-1px);outline:3px solid #c69a3b30}.option small{display:block;color:var(--muted);font-weight:400;margin-top:4px}.primary{background:var(--blue);color:#fff;text-align:center;border:0}.secondary{text-align:center;background:#fff;color:var(--blue)}.nav{display:flex;gap:10px;margin-top:24px}.nav>*{flex:1}label{display:block;font-weight:700;margin:18px 0 7px}input{width:100%;padding:16px;border:1px solid #ccd4e3;border-radius:13px;font:inherit}input:focus{outline:3px solid #163b8f25;border-color:var(--blue)}.notice{padding:13px 15px;background:#fff7df;border-left:4px solid var(--gold);border-radius:8px;margin:15px 0}.result{border:1px solid #e2e7ef;border-radius:16px;padding:18px;margin:13px 0}.result h2{margin:0;color:var(--blue)}.reasons{padding-left:20px;color:var(--muted)}.actions{display:grid;gap:10px}.modal{position:fixed;inset:0;background:#07132bd9;z-index:9;display:none;padding:12px}.modal.open{display:flex}.modalbox{background:white;border-radius:18px;max-width:1000px;width:100%;height:95vh;margin:auto;overflow:hidden;display:flex;flex-direction:column}.modalhead{padding:12px;display:flex;justify-content:space-between}.modal iframe{width:100%;flex:1;border:0}.error{color:#b42318}.check{display:flex;gap:10px;align-items:flex-start}.check input{width:auto;margin-top:4px}@media(max-width:520px){.shell{padding:12px}.card{border-radius:19px;min-height:calc(100vh - 115px)}.nav{position:sticky;bottom:8px}.modal{padding:0}.modalbox{height:100vh;border-radius:0}}
</style></head><body><main class="shell"><div class="brand"><div class="mark">GS</div><div>GRUPO SMILE<br><small>EVENTOS</small></div></div><div class="progress" aria-label="Progresso"><div class="bar" id="bar"></div></div><section class="card" id="app" aria-live="polite"></section></main><div class="modal" id="pdfModal" role="dialog" aria-modal="true"><div class="modalbox"><div class="modalhead"><strong>Orçamento completo</strong><button class="secondary" style="padding:8px 14px" onclick="closePdf()">Fechar</button></div><iframe id="pdfFrame" title="Orçamento em PDF"></iframe></div></div>
<script>
const catalogs=<?=json_encode($catalogos,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>, wa='<?=$wa?>';
const saved=JSON.parse(localStorage.getItem('smile_orcamento')||'{}'), state={step:0,answers:saved.answers||{},sid:saved.sid||crypto.randomUUID(),lead:saved.lead||null};
const $=s=>document.querySelector(s), app=$('#app'); function persist(){localStorage.setItem('smile_orcamento',JSON.stringify(state))} function metric(evento,dados={}){fetch('?page=orcamento_guiado&action=metric',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessao_uuid:state.sid,evento,dados})}).catch(()=>{})}
const types={casamento:'Casamento',bodas:'Bodas','15anos':'Festa de 15 anos',infantil:'Festa infantil'};
function opt(label,value,small=''){return `<button class="option" onclick='choose(${JSON.stringify(value)})'>${label}${small?`<small>${small}</small>`:''}</button>`} function back(){state.step=Math.max(0,state.step-1);persist();render()} function choose(v){const k=steps()[state.step].key;if(k)state.answers[k]=v;metric(k==='tipo_evento'?'tipo_evento':'etapa_respondida',{etapa:k});state.step++;persist();render()}
function steps(){let a=state.answers, s=[{key:'tipo_evento',title:'Qual evento você está planejando?',render:()=>Object.entries(types).map(([v,l])=>opt(l,v)).join('')},{key:'data_evento',title:'Qual é a data aproximada?',render:()=>`<label for="date">Data do evento</label><input id="date" type="date" value="${a.data_evento||''}"><div id="far"></div><button class="primary" onclick="saveInput('data_evento','date')">Continuar</button>`},{key:'convidados',title:'Quantas pessoas vocês imaginam convidar?',render:()=>`<label for="guests">Quantidade aproximada</label><input id="guests" type="number" min="1" max="3000" inputmode="numeric" value="${a.convidados||''}"><button class="primary" onclick="saveInput('convidados','guests')">Continuar</button>`}];
if(a.tipo_evento==='infantil') return [...s,{title:'Vamos encontrar o espaço ideal',render:()=>leadForm()}];
if(['casamento','bodas'].includes(a.tipo_evento))s.push({key:'cerimonia',title:a.tipo_evento==='bodas'?'Vocês pretendem realizar a renovação de votos no próprio espaço?':'Vocês pretendem realizar a cerimônia no próprio espaço?',render:()=>opt('Sim',true)+opt('Não',false)});
s.push({key:'perfil',title:a.tipo_evento==='15anos'?'Como vocês imaginam essa comemoração?':'Qual opção mais se aproxima do que vocês imaginam?',render:()=>opt(a.tipo_evento==='15anos'?'Mais objetiva':'Objetiva e econômica','economico','Uma comemoração completa, com investimento mais controlado.')+opt('Equilibrada','equilibrado','Boa estrutura, buffet e praticidade.')+opt('Mais completa','completo','Mais variedade, experiências e serviços incluídos.')});
if(a.tipo_evento==='15anos')s.push({key:'essencial',title:'Existe algum item que não pode faltar?',render:()=>['Pista e DJ','Decoração diferenciada','Fotos e atrações','Buffet mais completo','Ainda não sabemos'].map(x=>opt(x,x.toLowerCase())).join('')});
else s.push({key:'buffet',title:'Qual formato de buffet combina mais com vocês?',render:()=>['Jantar','Churrasco','Mini refeições','Ainda não sabemos'].map(x=>opt(x,x.toLowerCase())).join('')});
s.push({title:'Só falta identificar você',render:()=>leadForm()}); return s}
function saveInput(k,id){let v=$('#'+id).value;if(k==='convidados')v=Number(v);if(!v||v<1)return;state.answers[k]=v;state.step++;persist();render()}
function leadForm(){if(state.lead)return results();return `<p>Preencha os dados para liberar os catálogos e a recomendação.</p><label>Nome</label><input id="name" autocomplete="name"><label>WhatsApp</label><input id="phone" inputmode="tel" autocomplete="tel"><label>E-mail (opcional)</label><input id="email" type="email" autocomplete="email"><input id="website" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px"><label class="check"><input id="consent" type="checkbox"><span>Autorizo o contato do Grupo Smile e li a política de privacidade.</span></label><p class="error" id="err"></p><button class="primary" id="send" onclick="submitLead()">Ver minha recomendação</button>`}
async function submitLead(){let btn=$('#send');btn.disabled=true;btn.textContent='Preparando...';let body={sessao_uuid:state.sid,nome:$('#name').value,whatsapp:$('#phone').value,email:$('#email').value,website:$('#website').value,consentimento:$('#consent').checked,respostas:state.answers,origem:new URLSearchParams(location.search).get('utm_source')||'orcamento-guiado'};try{let r=await fetch('?page=orcamento_guiado&action=lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.erro);state.lead=j;persist();metric('conclusao',{lead_id:j.lead_id});render()}catch(e){$('#err').textContent=e.message;btn.disabled=false;btn.textContent='Ver minha recomendação'}}
function results(){let r=state.lead.recomendacao,a=state.answers;if(r.analise)return `<h1>Seu evento merece uma análise personalizada</h1><p>Para essa quantidade, nossa equipe vai preparar a melhor solução para vocês.</p>${warnings()}${contactActions()}`;let units=r.unidades, matches=catalogs.filter(c=>units.includes(c.unidade)&&c.tipo_evento===a.tipo_evento&&(a.tipo_evento==='infantil'||!r.pacote||c.nome.toLowerCase().includes(r.pacote.toLowerCase())));let cards=units.map((u,i)=>{let c=matches.find(x=>x.unidade===u)||catalogs.find(x=>x.unidade===u&&x.tipo_evento===a.tipo_evento);return `<article class="result"><small>${i?'SEGUNDA OPÇÃO':'RECOMENDAÇÃO PRINCIPAL'}</small><h2>${u}${r.pacote?' — '+r.pacote:''}</h2><p>${a.tipo_evento==='infantil'?(units.length===2?'Para essa quantidade, temos duas possibilidades. Conheça os espaços e veja qual combina mais com a comemoração.':`Para essa quantidade, a unidade indicada é a ${u}. Confira o catálogo completo e o vídeo do espaço.`):'Boa combinação entre capacidade, perfil da comemoração e praticidade.'}</p><ul class="reasons"><li>Compatível com a quantidade informada</li><li>Alinhado ao perfil escolhido</li><li>Estrutura completa para a celebração</li></ul>${c?.pdf_url?`<button class="primary" onclick='openPdf(${JSON.stringify(c.pdf_url)})'>Ver orçamento completo</button>`:'<p class="notice">Catálogo será disponibilizado pela equipe.</p>'}${(c?.video_url||c?.unidade_video)?`<button class="secondary" onclick='openVideo(${JSON.stringify(c.video_url||c.unidade_video)})'>Ver vídeo do espaço</button>`:''}</article>`}).join('');return `<h1>Encontramos ${units.length>1?'duas opções':'uma opção'} para vocês</h1>${cards}${warnings()}${contactActions()}`}
function warnings(){return `<div class="notice">Data sujeita à confirmação de disponibilidade pela equipe. Valores e condições também devem ser confirmados. Esta indicação não representa reserva.</div>`}function contactActions(){let text=encodeURIComponent(state.lead.whatsapp_texto);return `<div class="actions"><a class="primary" href="https://wa.me/${wa}?text=${text}" target="_blank" onclick="metric('whatsapp')">Falar com nossa equipe</a><a class="secondary" href="https://wa.me/${wa}?text=${encodeURIComponent(state.lead.whatsapp_texto+'\n\nQuero agendar uma visita.')}" target="_blank" onclick="metric('visita')">Quero agendar uma visita</a></div>`}
function openPdf(url){metric('pdf_aberto',{url});$('#pdfFrame').src=url+'#view=FitH&toolbar=1';$('#pdfModal').classList.add('open')}function closePdf(){$('#pdfModal').classList.remove('open');$('#pdfFrame').src=''}function openVideo(url){metric('video_reproduzido');window.open(url,'_blank','noopener')}
function render(){let s=steps();state.step=Math.min(state.step,s.length-1);let x=s[state.step];$('#bar').style.width=((state.step+1)/s.length*100)+'%';app.innerHTML=`<h1>${x.title}</h1><p>Uma pergunta por vez. Leva só alguns minutos.</p><div class="options">${x.render()}</div>${state.step?'<div class="nav"><button class="secondary" onclick="back()">← Voltar</button></div>':''}`;if(state.answers.data_evento){let d=new Date(state.answers.data_evento+'T12:00:00'),limit=new Date();limit.setMonth(limit.getMonth()+18);if(d>limit&&$('#far'))$('#far').innerHTML='<div class="notice">Nossa agenda de contratos ainda não está aberta para esse período, mas você pode conhecer as opções e valores atuais como referência.</div>'}}
addEventListener('beforeunload',()=>{if(!state.lead)metric('abandono',{etapa:state.step})});if(!saved.sid)metric('inicio');render();
</script></body></html>
