-- Migração: Adicionar colunas faltantes
-- Data: 2025-10-25 00:36:35

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_agenda_ver BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_agenda_meus BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_agenda_relatorios BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_gerir_eventos_outros BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_forcar_conflito BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_tarefas BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_lista BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_demandas BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_pagamentos BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_usuarios BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_portao BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_banco_smile BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_banco_smile_admin BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_notas_fiscais BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_estoque_logistico BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_dados_contrato BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS perm_uso_fiorino BOOLEAN DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cargo VARCHAR(100);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cpf VARCHAR(14);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS admissao_data DATE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS salario_base DECIMAL(10,2);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS pix_tipo VARCHAR(20);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS pix_chave VARCHAR(200);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS status_empregado VARCHAR(20) DEFAULT 'ativo';

ALTER TABLE lc_insumos ADD COLUMN IF NOT EXISTS nome VARCHAR(200);
ALTER TABLE lc_insumos ADD COLUMN IF NOT EXISTS categoria VARCHAR(100);
ALTER TABLE lc_insumos ADD COLUMN IF NOT EXISTS unidade_padrao VARCHAR(20);
ALTER TABLE lc_insumos ADD COLUMN IF NOT EXISTS custo_unitario DECIMAL(10,4);
ALTER TABLE lc_insumos ADD COLUMN IF NOT EXISTS fornecedor_id INTEGER;
ALTER TABLE lc_insumos ADD COLUMN IF NOT EXISTS substitutos JSONB;
ALTER TABLE lc_insumos ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ativo';

ALTER TABLE lc_listas ADD COLUMN IF NOT EXISTS categoria VARCHAR(100);
ALTER TABLE lc_listas ADD COLUMN IF NOT EXISTS tipo VARCHAR(20);
ALTER TABLE lc_listas ADD COLUMN IF NOT EXISTS payload JSONB;
ALTER TABLE lc_listas ADD COLUMN IF NOT EXISTS modo VARCHAR(20);
ALTER TABLE lc_listas ADD COLUMN IF NOT EXISTS token VARCHAR(100);

ALTER TABLE eventos ADD COLUMN IF NOT EXISTS titulo VARCHAR(200);
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS descricao TEXT;
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS data_inicio TIMESTAMP;
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS data_fim TIMESTAMP;
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS local VARCHAR(200);
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ativo';
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS observacoes TEXT;

ALTER TABLE comercial_degustacoes ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ativo';

