-- 091_financeiro_categorias.sql
-- Cadastro de categorias financeiras para lancamentos.

CREATE TABLE IF NOT EXISTS financeiro_categorias (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(180) NOT NULL,
    grupo VARCHAR(120) NOT NULL DEFAULT 'Geral',
    tipo VARCHAR(20) NOT NULL DEFAULT 'despesa',
    ordem INTEGER NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    descricao TEXT NULL,
    created_by INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (tipo, grupo, nome)
);

CREATE INDEX IF NOT EXISTS idx_financeiro_categorias_ativo
    ON financeiro_categorias(tipo, ativo, grupo, ordem, nome);

INSERT INTO financeiro_categorias (nome, grupo, tipo, ordem, ativo)
VALUES
    ('13o Salario', 'Geral', 'despesa', 10, TRUE),
    ('Agua e esgoto', 'Geral', 'despesa', 20, TRUE),
    ('Aluguel', 'Geral', 'despesa', 30, TRUE),
    ('Anuidade de cartao', 'Geral', 'despesa', 40, TRUE),
    ('Aquisicao de equipamentos', 'Geral', 'despesa', 50, TRUE),
    ('Assistencia Medica', 'Geral', 'despesa', 60, TRUE),
    ('Assistencia odontologica', 'Geral', 'despesa', 70, TRUE),
    ('Barmen', 'Geral', 'despesa', 80, TRUE),
    ('Bebidas', 'Geral', 'despesa', 90, TRUE),
    ('Bolo', 'Geral', 'despesa', 100, TRUE),
    ('Cartorio', 'Geral', 'despesa', 110, TRUE),
    ('Combustivel', 'Geral', 'despesa', 120, TRUE),
    ('Comissao de vendedores', 'Geral', 'despesa', 130, TRUE),
    ('Custos Eventos', 'Geral', 'despesa', 140, TRUE),
    ('Decoracao', 'Geral', 'despesa', 150, TRUE),
    ('Devolucao Cliente', 'Geral', 'despesa', 160, TRUE),
    ('DJ', 'Geral', 'despesa', 170, TRUE),
    ('Doces', 'Geral', 'despesa', 180, TRUE),
    ('Emprestimos', 'Geral', 'despesa', 190, TRUE),
    ('Energia eletrica', 'Geral', 'despesa', 200, TRUE),
    ('Escritorio', 'Geral', 'despesa', 210, TRUE),
    ('Fornecedores', 'Geral', 'despesa', 220, TRUE),
    ('Frutas congeladas', 'Geral', 'despesa', 230, TRUE),
    ('Gelo', 'Geral', 'despesa', 240, TRUE),
    ('Horas Extras', 'Geral', 'despesa', 250, TRUE),
    ('Hort Frut', 'Geral', 'despesa', 260, TRUE),
    ('Insumos', 'Geral', 'despesa', 270, TRUE),
    ('Internet', 'Geral', 'despesa', 280, TRUE),
    ('Investimentos', 'Geral', 'despesa', 290, TRUE),
    ('Alvara', 'Impostos', 'despesa', 10, TRUE),
    ('INSS', 'Impostos', 'despesa', 20, TRUE),
    ('Iof', 'Impostos', 'despesa', 30, TRUE),
    ('IPTU', 'Impostos', 'despesa', 40, TRUE),
    ('IPVA', 'Impostos', 'despesa', 50, TRUE),
    ('IR', 'Impostos', 'despesa', 60, TRUE),
    ('IRPJ', 'Impostos', 'despesa', 70, TRUE),
    ('Juros', 'Impostos', 'despesa', 80, TRUE),
    ('Simples Nacional', 'Impostos', 'despesa', 90, TRUE),
    ('Taxa de lixo', 'Impostos', 'despesa', 100, TRUE),
    ('Beneficios (V.A., VT, VR)', 'Pessoas e Equipe', 'despesa', 10, TRUE),
    ('Bonificacao Func.', 'Pessoas e Equipe', 'despesa', 20, TRUE),
    ('Freelancer', 'Pessoas e Equipe', 'despesa', 30, TRUE),
    ('Pro-Labore', 'Pessoas e Equipe', 'despesa', 40, TRUE),
    ('RH', 'Pessoas e Equipe', 'despesa', 50, TRUE),
    ('Salario', 'Pessoas e Equipe', 'despesa', 60, TRUE),
    ('Vale Transporte', 'Pessoas e Equipe', 'despesa', 70, TRUE),
    ('Agua', 'Despesas Fixas', 'despesa', 10, TRUE),
    ('Aluguel', 'Despesas Fixas', 'despesa', 20, TRUE),
    ('Aluguel de maquinas', 'Despesas Fixas', 'despesa', 30, TRUE),
    ('Assistencia Juridica', 'Despesas Fixas', 'despesa', 40, TRUE),
    ('Contabilidade', 'Despesas Fixas', 'despesa', 50, TRUE),
    ('Convenio medico', 'Despesas Fixas', 'despesa', 60, TRUE),
    ('Distribuicao de lucros', 'Despesas Fixas', 'despesa', 70, TRUE),
    ('Financiamento Carro', 'Despesas Fixas', 'despesa', 80, TRUE),
    ('Fundo de emergencia', 'Despesas Fixas', 'despesa', 90, TRUE),
    ('Luz', 'Despesas Fixas', 'despesa', 100, TRUE),
    ('Manutencao', 'Despesas Fixas', 'despesa', 110, TRUE),
    ('Medicina do Trabalho', 'Despesas Fixas', 'despesa', 120, TRUE),
    ('Telefone', 'Despesas Fixas', 'despesa', 130, TRUE),
    ('Limpeza', 'Despesas Fixas', 'despesa', 140, TRUE),
    ('Manutencao de equipamentos', 'Despesas Fixas', 'despesa', 150, TRUE),
    ('Material de escritorio', 'Despesas Fixas', 'despesa', 160, TRUE),
    ('Mini Lanchinhos', 'Despesas Fixas', 'despesa', 170, TRUE),
    ('Obras - Antiga e nova', 'Despesas Fixas', 'despesa', 180, TRUE),
    ('Pao / Padaria', 'Despesas Fixas', 'despesa', 190, TRUE),
    ('Passagem aereas', 'Despesas Fixas', 'despesa', 200, TRUE),
    ('Publicidade', 'Despesas Fixas', 'despesa', 210, TRUE),
    ('Rescisoes trabalhistas', 'Despesas Fixas', 'despesa', 220, TRUE),
    ('Salgados', 'Despesas Fixas', 'despesa', 230, TRUE),
    ('Seguro Patrimonial', 'Despesas Fixas', 'despesa', 240, TRUE),
    ('Sistemas em geral', 'Despesas Fixas', 'despesa', 250, TRUE),
    ('Taxas bancarias', 'Despesas Fixas', 'despesa', 260, TRUE),
    ('Taxas Cobranca', 'Despesas Fixas', 'despesa', 270, TRUE),
    ('Taxas Maquininhas', 'Despesas Fixas', 'despesa', 280, TRUE),
    ('Telefone celular', 'Despesas Fixas', 'despesa', 290, TRUE),
    ('Telefone fixo', 'Despesas Fixas', 'despesa', 300, TRUE),
    ('Toalhas', 'Despesas Fixas', 'despesa', 310, TRUE),
    ('Translado', 'Despesas Fixas', 'despesa', 320, TRUE),
    ('Transportes (Uber e etc)', 'Despesas Fixas', 'despesa', 330, TRUE),
    ('Treinamentos', 'Despesas Fixas', 'despesa', 340, TRUE),
    ('Uber', 'Despesas Fixas', 'despesa', 350, TRUE),
    ('Vale Alimentacao', 'Despesas Fixas', 'despesa', 360, TRUE),
    ('Vale Transporte', 'Despesas Fixas', 'despesa', 370, TRUE)
ON CONFLICT (tipo, grupo, nome) DO UPDATE SET
    ordem = EXCLUDED.ordem,
    ativo = TRUE,
    updated_at = NOW();
