-- =====================================================
-- SCRIPT COMPLETO PARA GARANTIR ESTRUTURA DA TABELA usuarios
-- Este script é IDEMPOTENTE - pode ser executado múltiplas vezes sem erro
-- =====================================================

-- 1. GARANTIR QUE A TABELA EXISTE
CREATE TABLE IF NOT EXISTS usuarios (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    senha VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 2. ADICIONAR COLUNAS OBRIGATÓRIAS (se não existirem)
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS login VARCHAR(100),
ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS perfil VARCHAR(20) DEFAULT 'OPER' CHECK (perfil IN ('ADM', 'GERENTE', 'OPER', 'CONSULTA'));

-- 3. ADICIONAR COLUNAS RH (se não existirem)
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS cpf VARCHAR(14),
ADD COLUMN IF NOT EXISTS cargo VARCHAR(100),
ADD COLUMN IF NOT EXISTS admissao_data DATE,
ADD COLUMN IF NOT EXISTS salario_base NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS pix_tipo VARCHAR(20),
ADD COLUMN IF NOT EXISTS pix_chave VARCHAR(255),
ADD COLUMN IF NOT EXISTS status_empregado VARCHAR(20) DEFAULT 'ativo' CHECK (status_empregado IN ('ativo', 'inativo'));

-- 4. ADICIONAR PERMISSÕES DA SIDEBAR (se não existirem)
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS perm_agenda BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_comercial BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_eventos BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_eventos_realizar BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_logistico BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_configuracoes BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_cadastros BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_financeiro BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_administrativo BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_rh BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_banco_smile BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_banco_smile_admin BOOLEAN DEFAULT FALSE;

-- 5. ADICIONAR PERMISSÕES ESPECÍFICAS (se não existirem)
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS perm_usuarios BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_pagamentos BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_tarefas BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_demandas BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_portao BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_notas_fiscais BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_estoque_logistico BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_dados_contrato BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_uso_fiorino BOOLEAN DEFAULT FALSE;

-- 6. VERIFICAR ESTRUTURA FINAL
SELECT 
    '=== ESTRUTURA FINAL DA TABELA usuarios ===' as info,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'usuarios' 
ORDER BY ordinal_position;
